# -*- coding: utf-8 -*-
    import sys, os, json, hashlib
    sys.path.insert(0, r"C:\Users\LENOVO\Desktop\XExam - Copy")
    os.chdir(r"C:\Users\LENOVO\Desktop\XExam - Copy")
    import app
    app.init_db()
    c = app.get_db()
    admin = c.execute("SELECT id FROM users WHERE username='admin'").fetchone()
    admin_id = admin['id'] if admin else 1
    subjects = {
    'Toan': {'time': 90, 'qs': [
    {'c':'Ham so y=x^3-3x^2+2 co bao nhieu diem cuc tri?','t':'mc','a':'0','b':'1','cc':'2','d':'3','ans':'C'},
    {'c':'Tap xac dinh cua y=log2(x-1):','t':'mc','a':'(1;+inf)','b':'[1;+inf)','cc':'(0;+inf)','d':'(-inf;1)','ans':'A'},
    {'c':'Nguyen ham f(x)=2x+1:','t':'mc','a':'x^2+x+C','b':'x^2+C','cc':'2x^2+x+C','d':'x+C','ans':'A'},
    {'c':'Tich phan 2f(x)dx (0->1) biet f(x)dx=3:','t':'mc','a':'3','b':'6','cc':'9','d':'12','ans':'B'},
    {'c':'z=3+4i co modun:','t':'mc','a':'3','b':'4','cc':'5','d':'7','ans':'C'},
    {'c':'2^x=8, x=?','t':'mc','a':'2','b':'3','cc':'4','d':'8','ans':'B'},
    {'c':'V hinh chop S.ABCD day vuong canh a, SA=a:','t':'mc','a':'a^3/3','b':'a^3/6','cc':'a^3','d':'a^3/2','ans':'A'},
    {'c':'KC tu O den MP x+2y-2z+3=0:','t':'mc','a':'1','b':'2','cc':'3','d':'3/5','ans':'A'},
    {'c':'CSC u1=2,d=3. u10=?','t':'mc','a':'27','b':'29','cc':'30','d':'32','ans':'B'},
    {'c':'log2(3)=a. log2(12)=?','t':'mc','a':'a+2','b':'2a','cc':'3a','d':'a+1','ans':'A'},
    {'c':'y=(x+1)/(x-2) tiem can dung:','t':'mc','a':'x=-1','b':'x=1','cc':'x=2','d':'x=-2','ans':'C'},
    {'c':'DT mat cau ban kinh R:','t':'mc','a':'2piR2','b':'4piR2','cc':'piR2','d':'3piR2','ans':'B'},
    {'c':'a=(1;2;-1),b=(2;-1;3). a.b=?','t':'mc','a':'-3','b':'3','cc':'-1','d':'1','ans':'A'},
    {'c':'x^2+y^2=9 ban kinh:','t':'mc','a':'9','b':'3','cc':'sqrt9','d':'81','ans':'B'},
    {'c':'y=x^4-2x^2+1 dong bien:','t':'mc','a':'(-1;0)','b':'(0;1)','cc':'(-1;1)','d':'(1;+inf)','ans':'D'},
    {'c':'Tinh phan (2x+1)dx (0->2)=?','t':'es','ans':'6'},
    {'c':'3^x=27. x=?','t':'es','ans':'3'},
    {'c':'Hinh tru r=3,h=4. V=? (pi=3.14)','t':'es','ans':'113.04'},
    {'c':'lim(3x^2+1)/(x^2-2) x->+inf=?','t':'es','ans':'3'},
    {'c':'Lien hop z=2-3i la?','t':'es','ans':'2+3i'},
    ]},
    'Vat ly': {'time': 50, 'qs': [
    {'c':'Don vi cuong do dong dien:','t':'mc','a':'Volt','b':'Ampe','cc':'Ohm','d':'Watt','ans':'B'},
    {'c':'F=k*q1*q2/r^? (Coulomb)','t':'mc','a':'r^2','b':'r','cc':'r^3','d':'2r','ans':'A'},
    {'c':'Van toc song dien tu chan khong:','t':'mc','a':'3x10^6','b':'3x10^8','cc':'340','d':'3x10^5','ans':'B'},
    {'c':'Quang dien la:','t':'mc','a':'e bi but ra khi AS','b':'Phat sang','cc':'Nhieu xa','d':'Phan xa','ans':'A'},
    {'c':'f dao dong cuong buc:','t':'mc','a':'f rieng','b':'f bat ky','cc':'f luc cuong buc','d':'0','ans':'C'},
    {'c':'T con lac don phu thuoc:','t':'mc','a':'A,m','b':'l,g','cc':'m,g','d':'A,l','ans':'B'},
    {'c':'PU hat nhan toa nhiet co:','t':'mc','a':'Do hut khoi +','b':'Do hut khoi -','cc':'Khong HK','d':'m tang','ans':'A'},
    {'c':'RLC cong huong khi:','t':'mc','a':'R=0','b':'ZL=ZC','cc':'ZL>ZC','d':'ZL<ZC','ans':'B'},
    {'c':'AS buoc song ngan nhat:','t':'mc','a':'Do','b':'Vang','cc':'Luc','d':'Tim','ans':'D'},
    {'c':'hf=A+Wd. A la:','t':'mc','a':'Dong nang','b':'Cong thoat','cc':'NL photon','d':'The nang','ans':'B'},
    {'c':'x=5cos(2pi*t). Bien do:','t':'mc','a':'2cm','b':'5cm','cc':'10cm','d':'2pi','ans':'B'},
    {'c':'Song co truyen trong:','t':'mc','a':'Chan khong','b':'MT vat chat','cc':'Ca hai','d':'Ran','ans':'B'},
    {'c':'Tu cam khi:','t':'mc','a':'I khong doi','b':'I bien thien','cc':'I=0','d':'q dung yen','ans':'B'},
    {'c':'Tia X buoc song:','t':'mc','a':'Lon hon AS','b':'Ngan hon AS','cc':'Bang AS','d':'KXD','ans':'B'},
    {'c':'Luc Lorentz phuong:','t':'mc','a':'Cung v','b':'Cung B','cc':'Vuong goc v va B','d':'Bat ky','ans':'C'},
    {'c':'m=2kg roi, g=10. v sau 3s=? m/s','t':'es','ans':'30'},
    {'c':'R=10,I=2. P=? W','t':'es','ans':'40'},
    {'c':'Buoc song f=100MHz=? m','t':'es','ans':'3'},
    {'c':'Con lac l=1,g=10. T=?','t':'es','ans':'2.0'},
    {'c':'Wd electron v=10^6=? x10^-19 J','t':'es','ans':'4.6'},
    ]},
    'Tieng Anh': {'time': 60, 'qs': [
    {'c':'She ___ to school every day.','t':'mc','a':'go','b':'goes','cc':'going','d':'gone','ans':'B'},
    {'c':'If I ___ you, I would study harder.','t':'mc','a':'am','b':'was','cc':'were','d':'be','ans':'C'},
    {'c':'The book ___ by millions.','t':'mc','a':'has read','b':'has been read','cc':'have been read','d':'is reading','ans':'B'},
    {'c':'He is the man ___ car was stolen.','t':'mc','a':'who','b':'whom','cc':'whose','d':'which','ans':'C'},
    {'c':'Different: thought/though/through/thorough','t':'mc','a':'thought','b':'though','cc':'through','d':'thorough','ans':'B'},
    {'c':'By the time we arrived, the movie ___.','t':'mc','a':'started','b':'has started','cc':'had started','d':'was starting','ans':'C'},
    {'c':'___ it was raining, we went.','t':'mc','a':'Because','b':'Although','cc':'Since','d':'When','ans':'B'},
    {'c':'Synonym of abundant:','t':'mc','a':'rare','b':'scarce','cc':'plentiful','d':'limited','ans':'C'},
    {'c':'She suggested ___ to cinema.','t':'mc','a':'go','b':'to go','cc':'going','d':'went','ans':'C'},
    {'c':'I wish I ___ speak French.','t':'mc','a':'can','b':'could','cc':'will','d':'may','ans':'B'},
    {'c':'He has worked here ___ 2020.','t':'mc','a':'for','b':'since','cc':'in','d':'from','ans':'B'},
    {'c':'Antonym of optimistic:','t':'mc','a':'hopeful','b':'confident','cc':'pessimistic','d':'cheerful','ans':'C'},
    {'c':'Not until she arrived ___ about keys.','t':'mc','a':'she realized','b':'did she realize','cc':'she did','d':'realized she','ans':'B'},
    {'c':'Children ___ play in park.','t':'mc','a':'use to','b':'used to','cc':'are used to','d':'using to','ans':'B'},
    {'c':'People say he is genius = ?','t':'mc','a':'He is said to be','b':'He said to be','cc':'He is say','d':'He was said be','ans':'A'},
    {'c':'She started 5 years ago => has ___ for 5 years','t':'es','ans':'been learning'},
    {'c':'If studied harder, he ___ exam','t':'es','ans':'would have passed'},
    {'c':'Noun of succeed?','t':'es','ans':'success'},
    {'c':'The more..the ___ (good)','t':'es','ans':'better'},
    {'c':'Passive: built 1990 => ___ in 1990','t':'es','ans':'was built'},
    ]},
    'Hoa hoc': {'time': 50, 'qs': [
    {'c':'Cau hinh e Na(Z=11):','t':'mc','a':'1s2 2s2 2p6 3s1','b':'1s2 2s2 2p6 3p1','cc':'1s2 2s2 2p7','d':'1s2 2s2 2p6','ans':'A'},
    {'c':'Chat dien ly manh:','t':'mc','a':'CH3COOH','b':'NaCl','cc':'H2O','d':'C2H5OH','ans':'B'},
    {'c':'KL khu manh nhat:','t':'mc','a':'Fe','b':'Cu','cc':'Na','d':'K','ans':'D'},
    {'c':'Xuc tac este hoa:','t':'mc','a':'NaOH','b':'H2SO4 dac','cc':'Fe2O3','d':'Al2O3','ans':'B'},
    {'c':'CT glucose:','t':'mc','a':'C12H22O11','b':'C6H12O6','cc':'(C6H10O5)n','d':'C2H5OH','ans':'B'},
    {'c':'Polime thien nhien:','t':'mc','a':'PE','b':'PVC','cc':'Cao su buna','d':'Tinh bot','ans':'D'},
    {'c':'Amino axit tinh:','t':'mc','a':'Axit','b':'Bazo','cc':'Luong tinh','d':'Trung tinh','ans':'C'},
    {'c':'Amin bac 1:','t':'mc','a':'CH3NH2','b':'(CH3)2NH','cc':'(CH3)3N','d':'C6H5NHCH3','ans':'A'},
    {'c':'DP NaCl mang ngan:','t':'mc','a':'Na+Cl2','b':'NaOH+Cl2+H2','cc':'NaCl+H2O','d':'Na+H2','ans':'B'},
    {'c':'Fe+HCl:','t':'mc','a':'FeCl3+H2','b':'FeCl2+H2','cc':'Fe2O3+H2','d':'FeCl2+H2O','ans':'B'},
    {'c':'Nuoc cung tam thoi:','t':'mc','a':'Ca,Mg,Cl','b':'Ca,Mg,HCO3','cc':'Na,K,SO4','d':'Fe,Cu','ans':'B'},
    {'c':'Chat beo = este cua:','t':'mc','a':'Glixerol+a.beo','b':'Etanol+a.beo','cc':'Metanol+axit','d':'Glix+HCl','ans':'A'},
    {'c':'Phenol tinh:','t':'mc','a':'Axit yeu','b':'Bazo manh','cc':'Trung tinh','d':'Axit manh','ans':'A'},
    {'c':'Thuy phan saccarozo:','t':'mc','a':'Glu','b':'Fruc','cc':'Glu+Fruc','d':'Tinh bot','ans':'C'},
    {'c':'Khi nha kinh:','t':'mc','a':'O2','b':'N2','cc':'CO2','d':'H2','ans':'C'},
    {'c':'pH HCl 0.01M=?','t':'es','ans':'2'},
    {'c':'CT muoi an?','t':'es','ans':'NaCl'},
    {'c':'KL FeCl2 tu 5.6g Fe=?g','t':'es','ans':'12.7'},
    {'c':'Mn oxi hoa trong KMnO4=?','t':'es','ans':'+7'},
    {'c':'V H2 tu 2.3g Na+H2O=?lit','t':'es','ans':'1.12'},
    ]},
    'Ngu van': {'time': 120, 'qs': [
    {'c':'Vo chong A Phu cua:','t':'mc','a':'To Hoai','b':'Kim Lan','cc':'NM Chau','d':'N Tuan','ans':'A'},
    {'c':'Vi Hanh dung but phap:','t':'mc','a':'Tuong trung','b':'Chau','cc':'Nhan hoa','d':'So sanh','ans':'B'},
    {'c':'Tay Tien tho cua:','t':'mc','a':'Quang Dung','b':'To Huu','cc':'Che Lan Vien','d':'Huy Can','ans':'A'},
    {'c':'NV chinh Chiec thuyen ngoai xa:','t':'mc','a':'Phung','b':'Mien','cc':'My','d':'Lien','ans':'A'},
    {'c':'Ai da dat ten cho dong song cua:','t':'mc','a':'N Tuan','b':'HPN Tuong','cc':'VT Phung','d':'Nam Cao','ans':'B'},
    {'c':'PC Nguyen Tuan:','t':'mc','a':'Gian di','b':'Tai hoa uyên bac','cc':'Tru tinh','d':'Hien thuc','ans':'B'},
    {'c':'Bai tho Song cua:','t':'mc','a':'Xuan Quynh','b':'HX Huong','cc':'Xuan Dieu','d':'Huy Can','ans':'A'},
    {'c':'Nguoi lai do Song Da the loai:','t':'mc','a':'Truyen ngan','b':'Tieu thuyet','cc':'Tuy but','d':'Kich','ans':'C'},
    {'c':'Ba cu Tu Vo nhat the hien:','t':'mc','a':'Nhan hau','b':'Phan khang','cc':'Kiem tinh','d':'Me con','ans':'A'},
    {'c':'Hai dua tre doi lap:','t':'mc','a':'AS-bong toi','b':'Giau-ngheo','cc':'Tre-gia','d':'Thi-que','ans':'A'},
    {'c':'PT bieu dat van nghi luan:','t':'mc','a':'Tu su','b':'Mieu ta','cc':'Nghi luan','d':'Bieu cam','ans':'C'},
    {'c':'Dat Nuoc cua:','t':'mc','a':'NK Diem','b':'ND Thi','cc':'CL Vien','d':'To Huu','ans':'A'},
    {'c':'Noi qua thuoc:','t':'mc','a':'An du','b':'Hoan du','cc':'Noi qua','d':'Nhan hoa','ans':'C'},
    {'c':'Rung xa nu cua:','t':'mc','a':'NT Thanh','b':'NM Chau','cc':'NH Thiep','d':'MV Khang','ans':'A'},
    {'c':'Hon Truong Ba cua:','t':'mc','a':'NH Tuong','b':'LQ Vu','cc':'VT Phung','d':'ND Thi','ans':'B'},
    {'c':'Chu de Tay Tien?','t':'es','ans':'Ve dep hao hoa lang man bi trang nguoi linh'},
    {'c':'Y nghia Chiec thuyen ngoai xa?','t':'es','ans':'Nhin cuoc song tu nhieu goc do'},
    {'c':'3 tac pham VH 1945-1975?','t':'es','ans':'Tay Tien, Viet Bac, Rung xa nu'},
    {'c':'Phep doi la gi?','t':'es','ans':'Goi ten SV bang ten khac co QH gan gui'},
    {'c':'PC chinh luan HCM?','t':'es','ans':'Lap luan chat che dan chung xac thuc'},
    ]},
    'Lich su': {'time': 50, 'qs': [
    {'c':'CM T8 thanh cong ngay:','t':'mc','a':'2/9/1945','b':'19/8/1945','cc':'1/5/1945','d':'22/12/1944','ans':'B'},
    {'c':'Dien Bien Phu ngay:','t':'mc','a':'30/4/1975','b':'7/5/1954','cc':'2/9/1945','d':'8/3/1965','ans':'B'},
    {'c':'Hiep dinh Paris nam:','t':'mc','a':'1972','b':'1973','cc':'1974','d':'1975','ans':'B'},
    {'c':'Thong nhat dat nuoc:','t':'mc','a':'2/9/1945','b':'7/5/1954','cc':'30/4/1975','d':'22/12/1976','ans':'C'},
    {'c':'LX phong ve tinh nam:','t':'mc','a':'1955','b':'1957','cc':'1961','d':'1969','ans':'B'},
    {'c':'ASEAN thanh lap:','t':'mc','a':'1965','b':'1967','cc':'1970','d':'1975','ans':'B'},
    {'c':'CTTG2 ket thuc:','t':'mc','a':'1944','b':'1945','cc':'1946','d':'1947','ans':'B'},
    {'c':'Can Vuong do:','t':'mc','a':'Ham Nghi+TTThuyet','b':'PB Chau','cc':'PC Trinh','d':'NAQ','ans':'A'},
    {'c':'DCSVN thanh lap:','t':'mc','a':'3/2/1930','b':'19/5/1930','cc':'2/9/1930','d':'1/5/1930','ans':'A'},
    {'c':'Ap Bac 1963 o:','t':'mc','a':'Dong Nai','b':'My Tho','cc':'Ben Tre','d':'Long An','ans':'B'},
    {'c':'Dong minh My:','t':'mc','a':'Lien Xo','b':'TQ','cc':'Anh','d':'Cuba','ans':'C'},
    {'c':'Berlin sup:','t':'mc','a':'1987','b':'1989','cc':'1991','d':'1993','ans':'B'},
    {'c':'CT lanh ket thuc:','t':'mc','a':'LX tan ra 1991','b':'Berlin 1989','cc':'My rut VN','d':'TQ doi moi','ans':'A'},
    {'c':'Dong Du do:','t':'mc','a':'PC Trinh','b':'PB Chau','cc':'LV Can','d':'HT Khang','ans':'B'},
    {'c':'LHQ thanh lap:','t':'mc','a':'1944','b':'1945','cc':'1946','d':'1950','ans':'B'},
    {'c':'Y nghia CM T8?','t':'es','ans':'Pha bo thong tri, lap VNDCCH'},
    {'c':'NN thang loi DBP?','t':'es','ans':'Lanh dao dung dan, tinh than anh dung'},
    {'c':'5 nuoc ASEAN?','t':'es','ans':'Thai Lan, Indonesia, Malaysia, Philippines, Singapore'},
    {'c':'ND Geneve 1954?','t':'es','ans':'Cong nhan doc lap VN, chia vi tuyen 17'},
    {'c':'CTTG2 KT chau Au khi?','t':'es','ans':'Duc dau hang 9/5/1945'},
    ]},
    'Sinh hoc': {'time': 50, 'qs': [
    {'c':'ADN co may mach:','t':'mc','a':'1','b':'2','cc':'3','d':'4','ans':'B'},
    {'c':'Phien ma tao:','t':'mc','a':'ADN','b':'mARN','cc':'Protein','d':'Lipit','ans':'B'},
    {'c':'Dot bien gen la:','t':'mc','a':'Bien doi NST','b':'Bien doi gen','cc':'So luong NST','d':'Kieu hinh','ans':'B'},
    {'c':'Da boi NST:','t':'mc','a':'2n','b':'3n+','cc':'n','d':'2n+1','ans':'B'},
    {'c':'CLTN tac dong:','t':'mc','a':'Ca the','b':'Quan the','cc':'Loai','d':'HST','ans':'A'},
    {'c':'Pha sang quang hop o:','t':'mc','a':'Chat nen','b':'Tilacoit','cc':'Ti the','d':'Nhan','ans':'B'},
    {'c':'Chuoi thuc an tu:','t':'mc','a':'Tieu thu','b':'San xuat','cc':'Phan giai','d':'An thit','ans':'B'},
    {'c':'Aa la:','t':'mc','a':'DH toi','b':'DH tran','cc':'Di hop','d':'KXD','ans':'C'},
    {'c':'PL doc lap cho:','t':'mc','a':'Gen cung NST','b':'Gen khac NST','cc':'Lien ket','d':'Gioi tinh','ans':'B'},
    {'c':'Ho hap TB may GD:','t':'mc','a':'2','b':'3','cc':'4','d':'5','ans':'B'},
    {'c':'Nguyen phan la:','t':'mc','a':'Giam nhiem','b':'Nguyen nhiem','cc':'TH protein','d':'Phien ma','ans':'B'},
    {'c':'Ky sinh:','t':'mc','a':'2 loi','b':'1 loi 1 hai','cc':'2 hai','d':'Trung tinh','ans':'B'},
    {'c':'Mang TB:','t':'mc','a':'ADN','b':'Lipit kep+protein','cc':'Tinh bot','d':'Xenlulozo','ans':'B'},
    {'c':'Anticodon o:','t':'mc','a':'mARN','b':'tARN','cc':'rARN','d':'snARN','ans':'B'},
    {'c':'HST gom:','t':'mc','a':'QX+sinh canh','b':'SV','cc':'MT','d':'DV+TV','ans':'A'},
    {'c':'Aa x Aa ti le KH?','t':'es','ans':'3:1'},
    {'c':'4 nucleotit ADN?','t':'es','ans':'A, T, G, C'},
    {'c':'SP duong phan?','t':'es','ans':'Axit piruvic'},
    {'c':'Bac DD cap 1?','t':'es','ans':'Sinh vat san xuat'},
    {'c':'Nhan to tien hoa QT nho?','t':'es','ans':'Bien dong di truyen'},
    ]},
    'Dia ly': {'time': 50, 'qs': [
    {'c':'VN o khu vuc:','t':'mc','a':'Dong Bac A','b':'Dong Nam A','cc':'Nam A','d':'Tay A','ans':'B'},
    {'c':'DT VN khoang:','t':'mc','a':'231k','b':'331k','cc':'431k','d':'131k','ans':'B'},
    {'c':'Song dai nhat VN:','t':'mc','a':'Hong','b':'Dong Nai','cc':'Cuu Long','d':'Ma','ans':'C'},
    {'c':'DB lon nhat VN:','t':'mc','a':'s.Hong','b':'s.Cuu Long','cc':'Thanh Nghe','d':'BT Thien','ans':'B'},
    {'c':'Khi hau VN:','t':'mc','a':'On doi','b':'Nhiet doi gio mua','cc':'Xich dao','d':'Han doi','ans':'B'},
    {'c':'TP lon nhat VN:','t':'mc','a':'HN','b':'HP','cc':'DN','d':'TP HCM','ans':'D'},
    {'c':'Vung KT nhat:','t':'mc','a':'DB sHong','b':'Dong Nam Bo','cc':'Tay Nguyen','d':'Bac TB','ans':'B'},
    {'c':'KS Quang Ninh:','t':'mc','a':'Dau mo','b':'Than da','cc':'Sat','d':'Vang','ans':'B'},
    {'c':'Rung nhiet doi o:','t':'mc','a':'Nhiet thap','b':'Mua lon nhiet cao','cc':'Kho','d':'Gio','ans':'B'},
    {'c':'Dan so VN 2024:','t':'mc','a':'80tr','b':'90tr','cc':'100tr','d':'110tr','ans':'C'},
    {'c':'Nganh GDP cao nhat:','t':'mc','a':'NN','b':'CN','cc':'DV','d':'Khoang san','ans':'C'},
    {'c':'Bien Dong phia:','t':'mc','a':'Bac','b':'Tay','cc':'Dong','d':'Nam','ans':'C'},
    {'c':'Tay Nguyen cay:','t':'mc','a':'Lua','b':'Ca phe','cc':'Mia','d':'Bong','ans':'B'},
    {'c':'DB sHong dat:','t':'mc','a':'Phu sa','b':'Bazan','cc':'Cat','d':'Phen','ans':'A'},
    {'c':'Nuoc DT lon nhat TG:','t':'mc','a':'TQ','b':'My','cc':'Canada','d':'Nga','ans':'D'},
    {'c':'3 KS chinh VN?','t':'es','ans':'Than, dau mo, sat'},
    {'c':'VN co ? tinh/TP','t':'es','ans':'63'},
    {'c':'3 song lon VN?','t':'es','ans':'Hong, Cuu Long, Dong Nai'},
    {'c':'Tinh DT lon nhat VN?','t':'es','ans':'Nghe An'},
    {'c':'Do thi hoa la gi?','t':'es','ans':'Tang ti le dan song thanh thi'},
    ]},
    'GDCD': {'time': 50, 'qs': [
    {'c':'Phap luat la:','t':'mc','a':'QT do NN ban hanh','b':'Dao duc','cc':'Tap quan','d':'Quy uoc','ans':'A'},
    {'c':'Binh dang truoc PL:','t':'mc','a':'Lam gi cung dc','b':'CD binh dang Q va NV','cc':'Chi nu','d':'Giau nhieu Q','ans':'B'},
    {'c':'Hien phap la:','t':'mc','a':'Luat thuong','b':'Luat co ban cao nhat','cc':'Nghi dinh','d':'Thong tu','ans':'B'},
    {'c':'Q tu do KD:','t':'mc','a':'HP','b':'Luat DN','cc':'Ca HP+LDN','d':'Khong co','ans':'C'},
    {'c':'Vi pham PL:','t':'mc','a':'Trai DD','b':'Trai PL co loi','cc':'Bat ky','d':'Chi toi pham','ans':'B'},
    {'c':'Bau cu tu tuoi:','t':'mc','a':'16','b':'18','cc':'20','d':'21','ans':'B'},
    {'c':'TNHS cho:','t':'mc','a':'HC','b':'Dan su','cc':'Toi pham','d':'Ky luat','ans':'C'},
    {'c':'Binh dang gioi:','t':'mc','a':'Giong nhau','b':'DV co hoi nhu nhau','cc':'Nu nhieu Q','d':'Nam nhieu Q','ans':'B'},
    {'c':'BK xam pham than the:','t':'mc','a':'Ko bi bat trai PL','b':'Lam gi cung dc','cc':'Ko lao dong','d':'Ko thue','ans':'A'},
    {'c':'Dao duc la:','t':'mc','a':'QT do PL','b':'QT le phai dieu thien','cc':'Tap quan','d':'Phong tuc','ans':'B'},
    {'c':'Bi mat thu tin thuoc:','t':'mc','a':'KT','b':'Tu do CN','cc':'CT','d':'VH','ans':'B'},
    {'c':'16t bi TNHS khi:','t':'mc','a':'Bat ky','b':'Toi rat/DB NG','cc':'Ko bao gio','d':'Toi nhe','ans':'B'},
    {'c':'Thuc hien PL may HT?','t':'mc','a':'2','b':'3','cc':'4','d':'5','ans':'C'},
    {'c':'Quoc hoi co quan:','t':'mc','a':'Hanh phap','b':'Tu phap','cc':'Lap phap','d':'Kiem sat','ans':'C'},
    {'c':'Muc dich PL:','t':'mc','a':'Loi ich CN','b':'Trat tu XH','cc':'Trung phat','d':'Thue','ans':'B'},
    {'c':'4 HT thuc hien PL?','t':'es','ans':'Tuan thu, Thi hanh, Su dung, Ap dung'},
    {'c':'Q tu do ngon luan?','t':'es','ans':'Tu do bieu dat y kien'},
    {'c':'Phan biet DD va PL?','t':'es','ans':'PL do NN cuong che, DD do du luan XH'},
    {'c':'2 quyen CD trong HP?','t':'es','ans':'Hoc tap, lao dong'},
    {'c':'Tre em la duoi ? tuoi','t':'es','ans':'16'},
    ]},
    'Tin hoc': {'time': 50, 'qs': [
    {'c':'Nhi phan may chu so?','t':'mc','a':'8','b':'10','cc':'2','d':'16','ans':'C'},
    {'c':'1 Byte=? Bit','t':'mc','a':'4','b':'8','cc':'16','d':'32','ans':'B'},
    {'c':'CPU la:','t':'mc','a':'Central Process U','b':'Central Processing Unit','cc':'Computer PU','d':'Central Program U','ans':'B'},
    {'c':'Python in MH:','t':'mc','a':'echo','b':'printf','cc':'print()','d':'write()','ans':'C'},
    {'c':'So nguyen Python:','t':'mc','a':'float','b':'str','cc':'int','d':'bool','ans':'C'},
    {'c':'range(5) lap:','t':'mc','a':'4','b':'5','cc':'6','d':'10','ans':'B'},
    {'c':'RAM la:','t':'mc','a':'Chi doc','b':'Truy cap NN mat khi tat','cc':'Vinh vien','d':'Ko ghi','ans':'B'},
    {'c':'Sap xep don gian nhat:','t':'mc','a':'Quick','b':'Merge','cc':'Bubble','d':'Heap','ans':'C'},
    {'c':'IPv4 = ? bit','t':'mc','a':'16','b':'32','cc':'64','d':'128','ans':'B'},
    {'c':'SQL la:','t':'mc','a':'Simple QL','b':'Structured QL','cc':'System QL','d':'Standard QL','ans':'B'},
    {'c':'SQL truy van:','t':'mc','a':'INSERT','b':'UPDATE','cc':'SELECT','d':'DELETE','ans':'C'},
    {'c':'OS ma nguon mo:','t':'mc','a':'Windows','b':'macOS','cc':'Linux','d':'iOS','ans':'C'},
    {'c':'Python list:','t':'mc','a':'Bat bien','b':'Mutable','cc':'Const','d':'Ham','ans':'B'},
    {'c':'Binary search O(?):','t':'mc','a':'O(n)','b':'O(n^2)','cc':'O(logn)','d':'O(1)','ans':'C'},
    {'c':'HTML la:','t':'mc','a':'Ngon ngu LT','b':'Danh dau SVB','cc':'QTCSDL','d':'OS','ans':'B'},
    {'c':'13 = ? (nhi phan)','t':'es','ans':'1101'},
    {'c':'len("Hello")=?','t':'es','ans':'5'},
    {'c':'SELECT *..score>=8 nghia?','t':'es','ans':'Lay HS diem tu 8'},
    {'c':'1GB=?MB','t':'es','ans':'1024'},
    {'c':'[1,2,3].append(4)=?','t':'es','ans':'[1, 2, 3, 4]'},
    ]},
    }
    created = 0
    for subject, data in subjects.items():
        title = "De on thi TN THPT - " + subject + " 2026"
        existing = c.execute("SELECT id FROM exams WHERE title=?", (title,)).fetchone()
        if existing:
            print("SKIP: " + title)
            continue
        cur = c.execute("INSERT INTO exams(title,subject,description,time_limit,total_score,created_by,is_open,max_attempts,shuffle_questions,teacher_approved) VALUES(?,?,?,?,?,?,?,?,?,?)", (title, subject, "De on thi TN THPT 2026 - Co dap an", data['time'], 10, admin_id, 1, 999, 1, 1))
        eid = cur.lastrowid
        for i, q in enumerate(data['qs'], 1):
            qtype = 'multiple_choice' if q['t'] == 'mc' else 'essay'
            score = 0.5 if qtype == 'multiple_choice' else 1.0
            c.execute("INSERT INTO questions(exam_id,question_number,type,content,option_a,option_b,option_c,option_d,correct_answer,score) VALUES(?,?,?,?,?,?,?,?,?,?)", (eid, i, qtype, q['c'], q.get('a',''), q.get('b',''), q.get('cc',''), q.get('d',''), q.get('ans',''), score))
        created += 1
        print("OK: " + title + " (" + str(len(data['qs'])) + " cau) ID=" + str(eid))
    c.commit()
    c.close()
    print("TONG: " + str(created) + " de thi!")
    